[package]
name = "xkcd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
env_logger = "0.11.8"
image = "0.25.6"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
ureq = { version = "3.0.11", features = ["json"] }
